# https://zensical.org

[project]
site_name = "Vorburger.ch's Agentic AI Assistant"
site_url = "https://ai.vorburger.ch"
repo_url = "https://github.com/vorburger/aifiles"
edit_uri = "edit/main/docs/"
copyright = "Copyright &copy; 2025 Michael Vorburger.ch <https://www.vorburger.ch>"

nav = [
  { "Home" = "index.md" },
  { "Usage" = [
    { "Install" = "install.md" },
    { "Use" = "use.md" },
  ]},
  { "Skills" = [
    { "Overview" = "skills/index.md" },
    { "Abbreviations" = "skills/abbreviations.md" },
    { "Bash Conventions" = "skills/bash-conventions.md" },
    { "Dependency Management" = "skills/dependency-management.md" },
    { "File Naming Conventions" = "skills/file-naming-conventions.md" },
    { "Git Commit Messages" = "skills/git-commit-messages.md" },
    { "Git Repositories" = "skills/git-repositories.md" },
    { "Git Workflow" = "skills/git-workflow.md" },
    { "Install Nix" = "skills/install-nix.md" },
    { "Java Conventions" = "skills/java-conventions.md" },
    { "Markdown Conventions" = "skills/markdown-conventions.md" },
    { "Nix" = "skills/nix.md" },
    { "Nix Update" = "skills/nix-update.md" },
    { "Preferred Tools" = "skills/preferred-tools.md" },
    { "Scripting Conventions" = "skills/scripting.md" },
    { "Skills" = "skills/skills.md" },
    { "Testing Projects" = "skills/testing.md" },
    { "TypeScript & Code Conventions" = "skills/typescript-conventions.md" },
    { "Vorburger Profile" = "skills/vorburger-profile.md" }
    ]},
  { "Development" = [
    { "Files & Directory" = "files.md" },
  ]},
]

[project.theme]
logo = "images/logo.png"
favicon = "images/logo.png"
language = "en"
features = [
  "content.action.edit",
  "content.code.copy",
  "navigation.footer",
  "navigation.instant",
  "navigation.tracking",
  "navigation.expand",
  # "navigation.path",
  "navigation.top",
  "navigation.tabs",
  "search.highlight",
]

[[project.theme.palette]]
scheme = "slate"
toggle.icon = "material/brightness-7"
toggle.name = "Switch to light mode"

[[project.theme.palette]]
scheme = "default"
toggle.icon = "material/brightness-4"
toggle.name = "Switch to dark mode"
